services:
  db:
    image: "mysql:oraclelinux9"
    container_name: 4onwheels-db
    restart: always
    ports:
      - "3307:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=rootpassword123"
      - "MYSQL_DATABASE=4onwheels"
    volumes:
      - mysql_db:/var/lib/sql
  app:
    build: .
    restart: always
    container_name: 4onwheels-app
    environment:
      - "GEMINI_API_KEY=AIzaSyAr-WJJDA_FyQNthafuygCa1LWZPyWBpug"
    ports:
      - "8080:8080"
    depends_on:
      - db


volumes:
  mysql_db:
